// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoRental.Data;

namespace VideoRental.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210624091922_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("VideoRental.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<int>("MaximumAge")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("VideoTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Years")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VideoTypeId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Drama",
                            MaximumAge = 0,
                            Title = "Diary of a Chambermaid",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Action",
                            MaximumAge = 0,
                            Title = "Perfect Sense",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            MaximumAge = 0,
                            Title = "Secret of the Grain, The (La graine et le mulet)",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Action",
                            MaximumAge = 0,
                            Title = "The Emperor's Candlesticks",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Action",
                            MaximumAge = 0,
                            Title = "Over the Brooklyn Bridge",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Comedy",
                            MaximumAge = 0,
                            Title = "Razortooth",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Drama",
                            MaximumAge = 0,
                            Title = "Septième juré, Le",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Romance",
                            MaximumAge = 0,
                            Title = "Layer Cake",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Comedy",
                            MaximumAge = 0,
                            Title = "Moon 44",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Horror",
                            MaximumAge = 0,
                            Title = "Shadow, The",
                            VideoTypeId = 1,
                            Years = 0
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Drama",
                            MaximumAge = 14,
                            Title = "Eva",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Regular",
                            MaximumAge = 12,
                            Title = "Mumia Abu-Jamal: A Case for Reasonable Doubt?",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Romance",
                            MaximumAge = 14,
                            Title = "Paris, France",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Horror",
                            MaximumAge = 10,
                            Title = "Vanishing, The (Spoorloos)",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Comedy",
                            MaximumAge = 11,
                            Title = "Diggstown",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Drama",
                            MaximumAge = 9,
                            Title = "Ring Two, The",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Romance",
                            MaximumAge = 6,
                            Title = "Black Tights (1-2-3-4 ou Les Collants noirs)",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Action",
                            MaximumAge = 12,
                            Title = "Few Good Men, A",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Drama",
                            MaximumAge = 13,
                            Title = "Misérables, Les",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Comedy",
                            MaximumAge = 14,
                            Title = "Officer and a Gentleman, An",
                            VideoTypeId = 2,
                            Years = 0
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Horror",
                            MaximumAge = 0,
                            Title = "YellowBrickRoad",
                            VideoTypeId = 3,
                            Years = 2
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Comedy",
                            MaximumAge = 0,
                            Title = "Singing Detective, The",
                            VideoTypeId = 3,
                            Years = 2
                        },
                        new
                        {
                            Id = 23,
                            Genre = "Comedy",
                            MaximumAge = 0,
                            Title = "Sorority Babes in the Slimeball Bowl-O-Rama",
                            VideoTypeId = 3,
                            Years = 1
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Comedy",
                            MaximumAge = 0,
                            Title = "Big Tease, The",
                            VideoTypeId = 3,
                            Years = 1
                        },
                        new
                        {
                            Id = 25,
                            Genre = "Romance",
                            MaximumAge = 0,
                            Title = "Time of Eve (Eve no jikan)",
                            VideoTypeId = 3,
                            Years = 2020
                        },
                        new
                        {
                            Id = 26,
                            Genre = "Drama",
                            MaximumAge = 0,
                            Title = "As Long as You've Got Your Health (Tant qu'on a la santé)",
                            VideoTypeId = 3,
                            Years = 2
                        },
                        new
                        {
                            Id = 27,
                            Genre = "Action",
                            MaximumAge = 0,
                            Title = "Red Hook Summer",
                            VideoTypeId = 3,
                            Years = 1
                        },
                        new
                        {
                            Id = 28,
                            Genre = "Horror",
                            MaximumAge = 0,
                            Title = "The Feathered Serpent",
                            VideoTypeId = 3,
                            Years = 1
                        },
                        new
                        {
                            Id = 29,
                            Genre = "Comedy",
                            MaximumAge = 0,
                            Title = "Little Lili (La petite Lili)",
                            VideoTypeId = 3,
                            Years = 2
                        },
                        new
                        {
                            Id = 30,
                            Genre = "Romance",
                            MaximumAge = 0,
                            Title = "Falling in Love",
                            VideoTypeId = 3,
                            Years = 1
                        });
                });

            modelBuilder.Entity("VideoRental.Entities.VideoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Rate")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VideoTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rate = 10,
                            Type = "Regular"
                        },
                        new
                        {
                            Id = 2,
                            Rate = 8,
                            Type = "Children’s Movie"
                        },
                        new
                        {
                            Id = 3,
                            Rate = 15,
                            Type = "New Release"
                        });
                });

            modelBuilder.Entity("VideoRental.Entities.Video", b =>
                {
                    b.HasOne("VideoRental.Entities.VideoType", "Type")
                        .WithMany()
                        .HasForeignKey("VideoTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
